### ISSUE TITLE
[FEATURES] [Modify Pop() function prototype of IResponseInputQueue]

### ISSUE THREAD

**Issue by ArthurVasseur** [martin-olivier/ZiAPI#12]
### Description

Hard to determine if `std::pair<Request, Context>` has been filled.
For example, if we implement the Pop function like this:
```cpp
std::pair<Request, Context> MyResponseInputQueue::Pop()
{
    if(myContainer.Size() == 0)
        return {};
    return myContainer.Pop();
}
```

If the function returns ` {}`, the default constructors of `Request` and `Context` will be called, which will make it harder to know if the `std::pair` has been filled.

### Describe the solution you'd like
Change the prototype of the Pop() function with:
```cpp
virtual bool Pop(std::pair<Request, Context> &req) = 0;
```
Now we can implement the new function :
```cpp
bool MyResponseInputQueue::Pop(std::pair<ziapi::http::Request, ziapi::http::Context> &req)
{
    if (myContainer.Size() == 0)
        return false;
    req = myContainer.Pop()
    return true;
}
```

And use it like that : 
```cpp

IResponseInputQueue* networkQueue = new ...;
std::pair<ziapi::http::Request, ziapi::http::Context> req;
while (networkQueue->Pop(req) {
    //process new request
 }

**Comment by rojasdiegopro** [comment]
We're down for that! Do you want to come up with a pull request or do you want us to do it? 😄

**Comment by ArthurVasseur** [comment]
Done, see #13
