### ISSUE TITLE
DELETE key word already used

### ISSUE THREAD

**Issue by DipStax** [martin-olivier/ZiAPI#16]
## [BUG] DELETE key word already used

`MSVC` already define `DELETE` (`winnt.h:8943`) and in `HttpConstants.hpp:10`, you try to modifie is value.

### Your environment

- OS: `Windows`
- Environement: `Visual Studio 2019` (occure on higher version)
- Branch: `main`

### Steps to reproduce

Error occur at compilation time.

### Expected behaviour

Compilete should end with no error.

### Actual behaviour

Compilation end with an error (see `Logs`)

### Logs

```
\ziapi-prefix\src\ziapi\include\ziapi\HttpConstants.hpp(10,16): error C2059:  erreur de syntaxe : 'constante'
```

### Proposed solution

Change the name of `ziapi::http::method::DELETE` to `ziapi::http::method::delete` or any other key word.

**Comment by rojasdiegopro** [comment]
Thank you very much, we're going to change the name of our constants according to the [C++ Google Coding Style](https://google.github.io/styleguide/cppguide.html) to fix the error in the next release.
