### ISSUE TITLE
String as key in http context

### ISSUE THREAD

**Issue by antwxne** [martin-olivier/ZiAPI#22]
### Description

"client" = structure client

mais les modules des autres groupes n'implementeront pas la value "client" sous forme de structure.

A voir si on peut pas imposer une nome / faire un enum

histoire que tout le monde utilise la meme chose

voir meme utiliser un data type comme celui du json

**Comment by rojasdiegopro** [comment]
This will be addressed in release `3.0.0`. Thank you very much for the feedback.
