### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by Breigner01** [martin-olivier/ZiAPI#3]
### Description

There is a typo in the README

### Your environment

* OS and version: doesn't matter
* branch that causes this issue: main

### Steps to reproduce

* Read the README

### Expected behaviour

No typo in README

### Actual behaviour

There is a typo

### Logs

None

### Proposed solution

Fix the following typo:
```
> :bulb: Don't forget to link with `libdl` on Unix is you use `dylib`:
```
```
> :bulb: Don't forget to link with `libdl` on Unix if you use `dylib`:
```

**Comment by martin-olivier** [comment]
Thanks @Breigner01 !
Fixed on https://github.com/martin-olivier/ZiAPI/commit/6fc2b0635b0cad1fe4efd95a8cc497539ee35f1d and https://github.com/martin-olivier/ZiAPI/commit/41dc355bd0eba98d68afca7641aff2a8e257b9c2
