### ISSUE TITLE
Returning references with AsString method

### ISSUE THREAD

**Issue by Pepiloto** [martin-olivier/ZiAPI#31]
### Description

Why returning a copy instead of a reference in the AsString method in struct Node ?
`String AsString() const { return std::get<String>(*this); }`
It's a good practice to return references instead of copies.

### Is your feature request related to a problem? Please describe.

I'm frustrated because I can't return const references with my configuration because it's causing a warning during compilation.

### Describe the solution you'd like

Return references or const references.

**Comment by rojasdiegopro** [comment]
We'll look into it today! Thanks
