### ISSUE TITLE
How to get out of pipeline when a module fail (or need to throw)?

### ISSUE THREAD

**Issue by arthur-fouquet** [martin-olivier/ZiAPI#32]
### Description

I was trying to figure how to "throw" from modules when an error occur or how to handle when you need to skip some modules because client is not logged or his method (POST, GET, ...) is not allowed on our server or anything like that.

### Proposed solution

Maybe it could be cool to have a way to throw an exception from the pipeline (maybe a class), the exception could possibly be catch in the core to handle response (with status code + error message if necessary, something like that) :)

**Comment by rojasdiegopro** [comment]
That's definitely an interesting idea.
First of all I think we need to more clearly define how ZIAPI handles exceptions.
Do you have examples of where and how exceptions could be used?

**Comment by antwxne** [comment]
## exemple:

```cpp
ziapi::Http::Response response;

try {
// pipeline
} catch (const ziapi::HTTPExecption &error) {
    response.status_code = error.code();
    response.reason = error.reason();
}
```
### Source

https://www.cs.jhu.edu/~erfan/files/apache.pdf 
page 18

**Comment by rojasdiegopro** [comment]
Mhm, I'm wondering if this is really necessary. At the moment you can simply do
```c++
response.Bootstrap(Code::kInternalServerError, reason::kInternalServerError);
```
To obtain similar results from within the module.

**Comment by antwxne** [comment]
> Mhm, I'm wondering if this is really necessary. At the moment you can simply do
> 
> ```c++
> response.Bootstrap(Code::kInternalServerError, reason::kInternalServerError);
> return;
> ```
> 
> To obtain similar results from within the module.

So it means that we need to check the current response code in all modules?

**Comment by rojasdiegopro** [comment]
Well, inside ZIAPI there are two kinds of pipeline.
The pre-processing pipeline and the post-processing pipeline.
If a module inside both pipelines encounters an error or fails, it shouldn't prevent all the other modules from running right? For example, you don't want an "Authentication Error" to prevent the response from being logged.
In the case of a handler, there is no pipeline for the handler. There is only one handler invoked per request.
So I don't think any module would need to check the response code.
What do you think?

**Comment by arthur-fouquet** [comment]
so how to prevent the execution of others modules if a module in preprocessing failed or throwed an error ? for exemple i got a module that allow only some methods for our server (GET and POST for exemple), atm, how do i cancel the pipeline if i receive a PUT method ?

**Comment by rojasdiegopro** [comment]
Then you can add a fallback module. Like a module that has the lowest priority possible and that generates `404` response for every request. That way if a request is not supported then it's handled "like an error".
Otherwise, we do not plan on implementing exceptions in the module pipeline at the moment.
However, if enough people want this feature too then we might re-consider.
